version: '3'
services:
  client-scoreboard:
    build:
      context: ./client-scoreboard
    environment:
      - NODE_ENV
    ports:
      - "3010:3010"
    depends_on:
      - "api"
    container_name: client-scoreboard
    volumes:
       - ./client-scoreboard:/usr/src/app/client-scoreboard
       - /usr/src/app/client-scoreboard/node_modules

  manager-dashboard:
    build:
      context: ./manager-dashboard
    environment:
      - NODE_ENV
    ports:
      - "3020:3020"
    depends_on:
      - "api"
    container_name: manager-dashboard
    volumes:
       - ./manager-dashboard:/usr/src/app/manager-dashboard
       - /usr/src/app/manager-dashboard/node_modules

  api:
    build:
      context: ./api
    environment:
      - NODE_ENV
    ports:
      - "5000:5000"
    container_name: api
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules