version: '3'
services:
  scoreboard-client:
    build:
      context: ./scoreboard-client
    environment:
      - NODE_ENV
    ports:
      - "3010:3010"
    depends_on:
      - "api"
    container_name: scoreboard-client
    volumes:
       - ./scoreboard-client:/usr/src/app/scoreboard-client
       - /usr/src/app/scoreboard-client/node_modules

  manager-dashboard:
    build:
      context: ./manager-dashboard
    environment:
      - NODE_ENV
    ports:
      - "3020:3020"
    depends_on:
      - "api"
    container_name: manager-dashboard
    volumes:
       - ./manager-dashboard:/usr/src/app/manager-dashboard
       - /usr/src/app/manager-dashboard/node_modules

  api:
    build:
      context: ./api
    environment:
      - NODE_ENV
    ports:
      - "5000:5000"
    container_name: api
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules