import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect } from 'react'
import { emitMessage } from '../services/socket'

const Home: NextPage = () => {
  useEffect(() => {
    setInterval(() => {
      const randomNumber = Math.floor(Math.random() * 1000)
      console.log(`sending random number ${randomNumber}`)

      emitMessage(randomNumber.toFixed())
    }, 2000)
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>sss</p>
    </div>
  )
}

export default Home
